name: GivePet
version: ${project.version}
main: me.lucyydotp.givepet.GivePet
api-version: 1.16
authors: [ lucyydotp ]
description: Transfer ownership of your pets to other people
website: https://lucyydotp.me
commands:
  givepet:
    usage: 'Usage: /givepet [player|cancel]'
    permission: "givepet.use"
    permission-message: "No permission!"

permissions:
  givepet.use:
    description: "Allows players to use the /givepet command"
    default: true
